name: Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'

      - name: Run Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar
          java -jar checkstyle-8.44-all.jar -c /path/to/checkstyle-config.xml src/

      - name: Compile
        run: |
          javac -cp .:./lib/junit-4.13.2.jar:./lib/hamcrest-core1.3.jar GradeTest.java GradeCalculator.java Grade.java
          # java -cp .:./lib/junit-4.13.2.jar:./lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore GradeTest
          # sudo service mysql start
          # sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS actionsJava;"
          # sudo mysql -u root -proot actionsJava < database.sql
          # javac Main.java
          # echo 1 | java -cp .:mysql-connector-java-8.2.0.jar Main
          # java -cp .:mysql-connector-java-8.2.0.jar Main < input.txt
        shell: bash
        
      - name: Test
        run: |
          # javac -cp .:./lib/junit-4.13.2.jar:./lib/hamcrest-core1.3.jar GradeTest.java GradeCalculator.java Grade.java
          java -cp .:./lib/junit-4.13.2.jar:./lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore GradeTest
          # sudo service mysql start
          # sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS actionsJava;"
          # sudo mysql -u root -proot actionsJava < database.sql
          # javac Main.java
          # echo 1 | java -cp .:mysql-connector-java-8.2.0.jar Main
          # java -cp .:mysql-connector-java-8.2.0.jar Main < input.txt
        shell: bash
